version: "3"                        # set skima version

services:                           # define service lists
  nginx:                            # define service
      build: requirements/nginx
      container_name: nginx
      ports:                        # set port
          - "443:443"
