# 컨테이너 별 조건 순서는 중요하지않음

version: "3"                        # set skima version

services:                           # define service lists
  nginx:                            # define service
      image: nginx
      build: requirements/nginx
      container_name: nginx
      volumes:
          - wp-data:/var/www/html
          #- ./data/html:/var/www/html # /host/path : /container/path
      ports:                        # set port
          - "443:443"
      networks:
          - inception_network

  mariadb:
      image: mariadb
      build: requirements/mariadb
      container_name: mariadb
      volumes:
          - db-data:/var/lib/mysql # named_volume_name : /container/path
      restart: always
      ports:
          - 3306
      networks:
          - inception_network
      env_file: .env
  
  wordpress:
      image: wordpress
      build: requirements/wordpress
      container_name: wordpress
      volumes:
          - wp-data:/var/www/html
      restart: always
      ports:
          - 9000
      networks:
          - inception_network
      depends_on:
          - mariadb

# n드라이브같은 클라우드를 만든다고 생각 >> 경로 지정해주자
# service에서 지정한 container path에 있는 내용이 home/yeslee/data/~ 로 이동

volumes:
    db-data:
        driver_opts:
            type: none
            device: /Users/yeslee/volume-test/db
            o: bind
    wp-data:
        driver_opts:
            type: none
            device: /Users/yeslee/volume-test/wp
            o: bind

networks:
    inception_network:
        # driver: bridge default값이기 때문에 안써도 무방
