all:
	gcc -L ./mlx -lmlx -framework AppKit -g3 -fsanitize=address \
		cub3d.h \
		srcs/parse_init.c \
		main.c \
		srcs/exception_handling.c \
		srcs/map_parsing_1.c \
		srcs/map_parsing_2.c \
		srcs/put_size_img_color.c \
		srcs/map_validation.c \
		include/get_next_line/get_next_line.c \
		include/get_next_line/get_next_line_utils.c \
		include/get_next_line/get_next_line.h \
		include/libft/ft_strncmp.c \
		include/libft/ft_split.c \
		include/libft/ft_strchr.c \
		include/libft/ft_strlen.c \
		include/libft/ft_strnstr.c \
		include/libft/ft_atoi.c \
		include/libft/ft_isdigit.c \
		include/libft/ft_strdup.c \
		include/libft/ft_size.c \
		include/libft/ft_calloc.c \
		include/libft/ft_memset.c \
		srcs/mlx_init.c \
		srcs/mlx_init_2.c \
		srcs/mlx_put.c \
		textured.c \
		srcs/bgm.c \
		srcs/input_key.c \
		srcs/draw_paint.c \
		srcs/save_bmp.c \
		srcs/draw_sprite.c
